language: r
cache: packages
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- "./_deploy.sh"
env:
  global:
    secure: iZcDYdC2SarLGfpl5R3K+TqyG9e0GDbKFWRMlGmysXpLzM2+KNXbpIdATdFib9tbFXDDvpGU+u2CfbYwDgAyQv25sjYLPr8UQaS7aZbZSIb7UUBXuWZt6kE/Z8n2FaLnYH/LzyoDhOL3d5wM7bkDk1gjKihlB9FCcnQHU3Y3ilY5POSM1qEUm2ke7cXNTNSs5C109U/XZYM8rpCAodSCESmSow/1RUWCRaoFkmKPgZgkc5uIsBfk/YZNoS+WNxQn4PYLpgtiageCwBEPJBXK3ZRd596bRuTFaHW0BM7luqkxEVyE/dedSnGap67y0ngETyTV5ROfd0r50qi6TlVz5HdkKazY5vpd+nNqlYUQlffU/zx9y2SNMdtcqA3o2ZWaHKGpk31ocX3kB3YyVFb5wHENdO4Nl4/COF+FE65YaEAZd3jQ0DHmMwxLN8WCnr6c550CrKwW6eOFBQxk77AmLoFPTUesOdj5nvzoNAugviAlAPTbz99yWRAGIT2j5C7jiZjuAwYl8OOEZvYUJP+ppRcqhL0B3xFoyyUOq1soVNlS08xtnCP+MluSIYLhhy8WUjCwiVBoK3MzeRt4Arc+N5tiZa7bo/ZoC41CzflnobxbYtlEKNqlAm7IzcktYZ7CNY13xpaUhbMsBZB1jXcUPBchLAF84kObZ6RatK049gc=
