language: r
cache: packages
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- "./_deploy.sh"
env:
  global:
    secure: LmlTZkn2lF/79qv83KlqMjLK55nBjVDyBXHu/jeukrahPXA+IIn+6g7i3+VdEjkdYWDnhlERJAkGre0KPv3fBDaujU79VHDRvJuJW56oKLPWCgR3aRcyPTIpw8qlxyo1bkUYCcUkqiNmUm6MUPxjoBrmZOlDh9BdTtG7kA3PTt5oBgTQaFBR5zaRAafDpDHO+shxP9ODnRnM+wxi35RwJ6HXAz6ZFOdn0JxgaR7rqhit3barETSDDU0MbMovcZAEEaW6VeC08OP40iE8SWKebB5fnJwtPY/jgOz8IIsnZaYSuL1ctNtdBc2LyF3U5FAH3wMpeHOfaPhAoPQLEEnUoyhJrV90KMNYcrUt4RdK47IlRBL8wnFMzgEOU3h9JgP+bkCaLZkan17v1+j33xH/jm8nQJPZH/BiJDGlNyUiehqr9CgF3C+0NTKeWa1/5HxMvhwspSYVTZYkFLBJuNsiAhHqtf4B9mAQVIlllVbepK0+brywZ7sui4uafxBNSLuy44Dt3oKWPqle/CvJXiToKJQoW0bGgK1/SiIWPchRtMQIMfuAjdldWrruWtA0PG7G7Li98yn/gTqNqrYN2dlTs1c2hNWaxoQUSqrsl+4ffz3zS9F5lQBoIW6rOCCzhpFZJu5K3QbBCp8zD2fOTCb4wyGwHyuHpGt6AHq79Ei1E3g=
